// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvInGQVkaiiT90zGYwV6acHPZJusDTyA',
    appId: '1:912072535467:web:83e74c78bd7d0e81a376ee',
    messagingSenderId: '912072535467',
    projectId: 'portfolio-79c4d',
    authDomain: 'portfolio-79c4d.firebaseapp.com',
    storageBucket: 'portfolio-79c4d.appspot.com',
    measurementId: 'G-YMGTCZMT2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGoTiD2WSVQthqCWPcQ-Rvh-1BhYkKOCI',
    appId: '1:912072535467:android:a96466d8a863c50ca376ee',
    messagingSenderId: '912072535467',
    projectId: 'portfolio-79c4d',
    storageBucket: 'portfolio-79c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjH_qd2N6SKCDyNYt3WH13q5-K8zxhCKo',
    appId: '1:912072535467:ios:5959b274d8f3d6baa376ee',
    messagingSenderId: '912072535467',
    projectId: 'portfolio-79c4d',
    storageBucket: 'portfolio-79c4d.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjH_qd2N6SKCDyNYt3WH13q5-K8zxhCKo',
    appId: '1:912072535467:ios:5959b274d8f3d6baa376ee',
    messagingSenderId: '912072535467',
    projectId: 'portfolio-79c4d',
    storageBucket: 'portfolio-79c4d.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHvInGQVkaiiT90zGYwV6acHPZJusDTyA',
    appId: '1:912072535467:web:ff85bd4f21461710a376ee',
    messagingSenderId: '912072535467',
    projectId: 'portfolio-79c4d',
    authDomain: 'portfolio-79c4d.firebaseapp.com',
    storageBucket: 'portfolio-79c4d.appspot.com',
    measurementId: 'G-VRJT2WEC8X',
  );
}
